// user
POST http://localhost:3000/auth/login
content-type: application/json

{
  "email":"208holmesz@gmail.com",
  "password": "lamlamlam"
}


###
POST http://localhost:3000/auth/register
content-type: application/json

{
  "email":"208holmesz@gmail.com",
  "password": "lamlamlam",
  "fullName":"Pham Tan Dat"
}

###
GET http://localhost:3000/auth/getAuth
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjA5ZmFiMmY0ZjQ2ZDkwMDEyN2MxODJlIiwiaWF0IjoxNjIxMjQwNjkyODMzLCJleHAiOjE2MjEzMjcwOTI4MzN9.78owfx4KMjSZPu-NsiquKfYrvAm4NQOtt1SaxbUXag8

###
POST http://localhost:3000/auth/verify
content-type: application/json

{
  "email":"208holmesz@gmail.com",
  "password": "lamlamlam",
  "otp":"422204"
}
// product
###
POST http://localhost:3005/product/createProduct
Content-Type: application/json

{
"Code": "78998874",
"Description": "a",
"FK_Category": "60a0c06c83d4831570267ba6",
"FK_Room": "609545b240430a16c8626a97",
"Guarantee": "12",
"Image": ["a", "a", "a"],
"Material": "a",
"Name": "a",
"Price": 1000000,
"Quantity": "1",
"Size": "a",
"Total": 2,
"tags":  ["ban an mo rong freya van da", "71304044", "mat ban mat gom van da"]
}

###
GET http://18.217.70.108/product/getAllProducts?limit=12&page=1
content-type: application/json

###
GET http://localhost:3000/product/getProductsByRoom
content-type: application/json

###
GET http://localhost:3000/product/getProductsByCategory?idCategory=60954e8f53a0fb4b2c0e6a13&limit=12&page=1
content-type: application/json

###
GET http://localhost:3000/product/getProduct/60a0bd8183d4831570267ba4
content-type: application/json

###
PUT http://localhost:3000/product/updateProduct/608b88d8bff79f20cc0c8b37
Content-Type: application/json

{
  
}

###
DELETE http://localhost:3000/product/deleteProduct/6095509f53a0fb4b2c0e6a24
Content-Type: application/json


//Room
###
POST  http://localhost:3000/room/createRoom
content-type: application/json

{
    "name": "Decoration and houseware"
}


###
GET http://localhost:3000/room/getRooms
content-type: application/json

###

GET http://localhost:3000/product/filter
content-type: application/json

###
GET http://localhost:3005/product/search?tags=
content-type: application/json

###
GET http://localhost:3000/product/filterByPrice?price=15967500
content-type: application/json

//category
###
POST  http://localhost:3000/category/createCategory
content-type: application/json

{
    "name": "Ban an go",
    "FK_Room": "6095465553a0fb4b2c0e6a0e"
}

###
GET http://localhost:3000/category/getCategory
content-type: application/json

###
PUT http://localhost:3000/category/updateCategory/608e3a100b7dde2c1cd4fcd8
content-type: application/json

{
  "name": "xe may dien"
}
###
DELETE http://localhost:3000/category/deleteCategory/6094fcfd285d634bc09451a9
content-type: application/json



# /product/getProductsByCategory?idCategory=60954e8f53a0fb4b2c0e6a13&limit=12&page=1
# /product/getProductsByCategory?idCategory=60954e8f53a0fb4b2c0e6a13&limit=12&page=1


###
POST  http://localhost:3000/cart/createCart
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjBhMjdkNDg4NWQxY2UxYjg4NzljZjAxIiwiaWF0IjoxNjIxNDM1MzM0MDg1LCJleHAiOjE2MjE1MjE3MzQwODV9.qzPj6BKd9YHjBjsDQ8RqridXDx5YQy4H9efN1dnlQZE

{
  
  "idProduct": "60a0bd243e3689468e6b366e",
  "total": 10
  
}

GET  http://localhost:3005/cart/getCart
content-type: application/json

// Interior Design
###
POST  http://localhost:3000/interiorDesign/createTypeInteriorDesign
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjBhMjdkNDg4NWQxY2UxYjg4NzljZjAxIiwiaWF0IjoxNjIxNDM1MzM0MDg1LCJleHAiOjE2MjE1MjE3MzQwODV9.qzPj6BKd9YHjBjsDQ8RqridXDx5YQy4H9efN1dnlQZE

{
  
  "name": "Biet thu"
}


###
POST  http://localhost:3000/interiorDesign/createInteriorDesign
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjBhMjdkNDg4NWQxY2UxYjg4NzljZjAxIiwiaWF0IjoxNjIxNDM1MzM0MDg1LCJleHAiOjE2MjE1MjE3MzQwODV9.qzPj6BKd9YHjBjsDQ8RqridXDx5YQy4H9efN1dnlQZE

{
  "title": "Thiết kế nội thất căn hộ 77m2 chung cư Smart City",

    "project":  "Chung cư 2 phòng ngủ",
    "style": "Scandinavian",
    "S": "77m2",
  "description": "Mỗi gia chủ lại có những nhu cầu thiết kế nội thất khác nhau khi tìm đến Nhà Đẹp. Với các khách hàng có kế hoạch cụ thể về ngân sách, Nhà Đẹp sẽ nghiên cứu và đưa ra giải pháp, phù hợp cả về chi phí lẫn đảm bảo công năng và sự tiện nghi cho căn hộ.",
  
      "img": "https://firebasestorage.googleapis.com/v0/b/cnpm-e5af3.appspot.com/o/Category%2FDuAn%2FchungCu%2Fsmartcity%2FBEP-PKHACH.jpg?alt=media&token=f1453db2-4642-448e-934d-bdcb2881d511",
      "content": "213212233",

  "FK_TypeInteriorDesign": "60a544536e6ee6238c0bcf0d"
}

###
GET http://localhost:3000/interiorDesign/getInteriorDesign
content-type: application/json

###
GET http://localhost:3000/interiorDesign/getInteriorDesignByType?idInteriorDesign=60a544536e6ee6238c0bcf0d&limit=12&page=1
content-type: application/json