// user
POST http://localhost:3005/auth/login
content-type: application/json

{
  "email":"lamhan3012@gmail.com",
  "password": "abcd1234"
}


###
POST http://localhost:3000/auth/register
content-type: application/json

{
  "email":"208holmesz@gmail.com",
  "password": "lamlamlam",
  "fullName":"Pham Tan Dat"
}

###
GET http://localhost:3000/auth/getAuth
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjA5ZmFiMmY0ZjQ2ZDkwMDEyN2MxODJlIiwiaWF0IjoxNjIxMjQwNjkyODMzLCJleHAiOjE2MjEzMjcwOTI4MzN9.78owfx4KMjSZPu-NsiquKfYrvAm4NQOtt1SaxbUXag8

###
POST http://localhost:3000/auth/verify
content-type: application/json

{
  "email":"208holmesz@gmail.com",
  "password": "lamlamlam",
  "otp":"422204"
}
// product
###
POST http://localhost:3000/product/createProduct
Content-Type: application/json

{
  "Name": "Bàn trà mặt đá Trivia",
        "Code": "81144029",
        "Size": "100x100x42",
        "Material": "Mặt đá, khung inox",
        "Quantity": "1 bàn tròn",
        "Guarantee": "Khung bảo hành 1 năm, mặt đá 2 năm",
        "Price": "21.290.000",
        "Description": "Dòng sản phẩm bàn trà cao cấp với mặt bàn bằng đá. Vân đá hài hòa, màu sắc trang nhã, kiểu dáng khung độc đáo, phù hợp với các không gian phòng khách cao cấp, sang trọng, thể hiện gu thẩm mỹ tinh tế của gia chủ.",
        "Image": "https://firebasestorage.googleapis.com/v0/b/cnpm-e5af3.appspot.com/o/Product%2FBanTra%2Fban%20tra%2019.jpg?alt=media&token=e085f3f2-87cc-4844-99d0-2a618c29f16d",
        "isStatus": "",
    "FK_Room": "6094fce7285d634bc09451a8",
    "FK_Category": "60954e8f53a0fb4b2c0e6a13"
}

###
GET http://18.217.70.108/product/getAllProducts?limit=12&page=1
content-type: application/json

###
GET http://localhost:3000/product/getProductsByRoom
content-type: application/json

###
GET http://localhost:3000/product/getProductsByCategory?idCategory=60954e8f53a0fb4b2c0e6a13&limit=12&page=1
content-type: application/json

###
GET http://localhost:8080/product/getProduct/60b897dedaa6ed1bc4a94680
content-type: application/json

###
PUT http://localhost:3000/product/updateProduct/608b88d8bff79f20cc0c8b37
Content-Type: application/json

{
  
}

###
DELETE http://localhost:3000/product/deleteProduct/6095509f53a0fb4b2c0e6a24
Content-Type: application/json


//Room
###
POST  http://localhost:3000/room/createRoom
content-type: application/json

{
    "name": "Decoration and houseware"
}


###
GET http://localhost:3000/room/getRooms
content-type: application/json

###

GET http://localhost:3000/product/filter
content-type: application/json

###
GET http://localhost:3005/product/search?tags=
content-type: application/json

###
GET http://localhost:3000/product/filterByPrice?price=15967500
content-type: application/json

//category
###
POST  http://localhost:3000/category/createCategory
content-type: application/json

{
    "name": "Ban an go",
    "FK_Room": "6095465553a0fb4b2c0e6a0e"
}

###
GET http://localhost:3000/category/getCategory
content-type: application/json

###
PUT http://localhost:3000/category/updateCategory/608e3a100b7dde2c1cd4fcd8
content-type: application/json

{
  "name": "xe may dien"
}
###
DELETE http://localhost:3000/category/deleteCategory/6094fcfd285d634bc09451a9
content-type: application/json



# /product/getProductsByCategory?idCategory=60954e8f53a0fb4b2c0e6a13&limit=12&page=1
# /product/getProductsByCategory?idCategory=60954e8f53a0fb4b2c0e6a13&limit=12&page=1


###
POST  http://localhost:3000/cart/createCart
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjBhMjdkNDg4NWQxY2UxYjg4NzljZjAxIiwiaWF0IjoxNjIxNDM1MzM0MDg1LCJleHAiOjE2MjE1MjE3MzQwODV9.qzPj6BKd9YHjBjsDQ8RqridXDx5YQy4H9efN1dnlQZE

{
  
  "idProduct": "60a0bd243e3689468e6b366e",
  "total": 10
  
}

// Interior Design
###
POST  http://localhost:3000/interiorDesign/createTypeInteriorDesign
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjBhMjdkNDg4NWQxY2UxYjg4NzljZjAxIiwiaWF0IjoxNjIxNDM1MzM0MDg1LCJleHAiOjE2MjE1MjE3MzQwODV9.qzPj6BKd9YHjBjsDQ8RqridXDx5YQy4H9efN1dnlQZE

{
  
  "name": "Biet thu"
}


###
POST  http://localhost:3000/interiorDesign/createInteriorDesign
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjBhMjdkNDg4NWQxY2UxYjg4NzljZjAxIiwiaWF0IjoxNjIxNDM1MzM0MDg1LCJleHAiOjE2MjE1MjE3MzQwODV9.qzPj6BKd9YHjBjsDQ8RqridXDx5YQy4H9efN1dnlQZE

{
  "title": "Thiết kế nội thất căn hộ 77m2 chung cư Smart City",

    "project":  "Chung cư 2 phòng ngủ",
    "style": "Scandinavian",
    "S": "77m2",
  "description": "Mỗi gia chủ lại có những nhu cầu thiết kế nội thất khác nhau khi tìm đến Nhà Đẹp. Với các khách hàng có kế hoạch cụ thể về ngân sách, Nhà Đẹp sẽ nghiên cứu và đưa ra giải pháp, phù hợp cả về chi phí lẫn đảm bảo công năng và sự tiện nghi cho căn hộ.",
  
      "img": "https://firebasestorage.googleapis.com/v0/b/cnpm-e5af3.appspot.com/o/Category%2FDuAn%2FchungCu%2Fsmartcity%2FBEP-PKHACH.jpg?alt=media&token=f1453db2-4642-448e-934d-bdcb2881d511",
      "content": "213212233",

  "FK_TypeInteriorDesign": "60a544536e6ee6238c0bcf0d"
}

###
GET http://localhost:3000/interiorDesign/getInteriorDesign
content-type: application/json

###
GET http://localhost:3000/interiorDesign/getInteriorDesignByType?idInteriorDesign=60a544536e6ee6238c0bcf0d&limit=12&page=1
content-type: application/json

//pending cart
###
POST  http://localhost:3005/pendingCart/createPendingCart
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjA5ZmFiMmY0ZjQ2ZDkwMDEyN2MxODJlIiwiaWF0IjoxNjIxNjkzOTQ0MjU4LCJleHAiOjE2MjE3ODAzNDQyNTh9.GParLcPS5oEM9dpdTbJF0w-Yzj1-OrpKQqSRYtZosBE

{
  
}

###
POST  http://18.217.70.108/pendingCart/changeStatus
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjBhMjdkNDg4NWQxY2UxYjg4NzljZjAxIiwiaWF0IjoxNjIxNDM1MzM0MDg1LCJleHAiOjE2MjE1MjE3MzQwODV9.qzPj6BKd9YHjBjsDQ8RqridXDx5YQy4H9efN1dnlQZE

  {
    "status": "ON_GOING",
    "idPackage":"60a9fde6debcc54d6538884c"
  }

###
POST  http://localhost:3005/pendingCart/admin/changeStatus
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjBhMjdkNDg4NWQxY2UxYjg4NzljZjAxIiwiaWF0IjoxNjIxNDM1MzM0MDg1LCJleHAiOjE2MjE1MjE3MzQwODV9.qzPj6BKd9YHjBjsDQ8RqridXDx5YQy4H9efN1dnlQZE

{
  "status": "ON_GOING",
  "idPackage":"60a9fde6debcc54d6538884c"
}

///admin/changeStatus
###
GET  http://localhost:3005/pendingCart/admin/getPendingCart?status=AWAIT_FOR_CONFIRMATION
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjBhMjdkNDg4NWQxY2UxYjg4NzljZjAxIiwiaWF0IjoxNjIxNDM1MzM0MDg1LCJleHAiOjE2MjE1MjE3MzQwODV9.qzPj6BKd9YHjBjsDQ8RqridXDx5YQy4H9efN1dnlQZE


###
GET  http://localhost:3005/pendingCart/customer/getPendingCart?status=
content-type: application/json
authorization: baszer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJQaGFtIFRhbiBEYXQiLCJkYXRhIjoiNjA5ZmFiMmY0ZjQ2ZDkwMDEyN2MxODJlIiwiaWF0IjoxNjIxNjk5OTMzMDQxLCJleHAiOjE2MjE3ODYzMzMwNDF9.KMBM_3AUmE8kVte1PKj2CFGFmJ43ov6_X8OrVYm-GE0