POST http://18.217.70.108:4000/auth/login
content-type: application/json

{
    "email": "sample5@gmail.com",
    "password": "lamlamlam"
}

###

POST http://18.217.70.108:4000/auth/register
content-type: application/json

{
  "username": "sample8@gmail.com",
  "password": "lamlamlam",
  "email":"sample8@gmail.com",
  "fullName":"Pham Tan Dat",
  "phone":"0947123456"
}

###
GET http://localhost:3333/auth/getAuth
content-type: application/json
